# Generated by Django 4.1.7 on 2023-03-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('calle', models.CharField(max_length=30)),
                ('numero', models.IntegerField()),
                ('ciudad', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Direcciones',
        ),
        migrations.RemoveField(
            model_name='home',
            name='nombre',
        ),
    ]
