# Generated by Django 4.1.7 on 2023-04-05 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppWeb', '0003_about_lugar_delete_direccion_delete_solicitud'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lugar',
        ),
    ]
