# Generated by Django 4.1.7 on 2023-04-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('lugar', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=1000)),
                ('imagen', models.ImageField(upload_to='Lugares/imagenes/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
