# Generated by Django 4.1.7 on 2023-04-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLugares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='autor',
            field=models.CharField(default='andres', max_length=30),
            preserve_default=False,
        ),
    ]
