# Generated by Django 4.1.7 on 2023-04-06 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppLugares', '0002_post_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('autor', models.CharField(max_length=30)),
                ('comentario', models.TextField()),
            ],
        ),
    ]
